<template lang="html">
	<div>
		<h3>Google AdSense</h3>
		<p>This website uses Google AdSense, a service for including advertisements from Google Inc. ("Google"). It is operated
			by Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p>
		<p>Google AdSense uses so-called "cookies", which are text files stored in your computer that enable an analysis of the
			way you use the website. Google AdSense also uses so-called web beacons (invisible graphics). Through these web beacons,
			information such as the visitor traffic on these pages can be evaluated.</p>
		<p>The information generated by cookies and web beacons relating to your use of this website (including your IP address),
			and delivery of advertising formats, is transmitted to a Google server in the US and stored there. This information
			can be passed on from Google to contracting parties of Google. However, Google will not merge your IP address with
			other data you have stored.</p>
		<p>AdSense cookies are stored based on Art. 6 (1) (f) DSGVO. The website operator has a legitimate interest in analyzing
			user behavior to optimize both its website and its advertising.</p>
		<p>You can prevent the installation of cookies by setting your browser software accordingly. Please be aware that in this
			case, you may not be able to make full use of all the features of this website. By using this website, you agree
			to the processing of data relating to you and collected by Google as described and for the purposes set out above.</p>
  </div>
</template>

<script lang="ts">
	export default {
		name: 'googleAdsense',
		props: [],
		mounted() {

		},
		data() {
			return {

			}
		},
		methods: {

		},
		computed: {

		}
}
</script>

<style scoped lang="scss">
	.google-adsense {

	}
</style>
