<template lang="html">
	<div>
		<h3>Google Analytics</h3>
		<p>This website uses Google Analytics, a web analytics service. It is operated by Google Inc., 1600 Amphitheatre Parkway,
			Mountain View, CA 94043, USA.</p>
		<p>Google Analytics uses so-called "cookies". These are text files that are stored on your computer and that allow an analysis
			of the use of the website by you. The information generated by the cookie about your use of this website is usually
			transmitted to a Google server in the USA and stored there.</p>
		<p>Google Analytics cookies are stored based on Art. 6 (1) (f) DSGVO. The website operator has a legitimate interest in
			analyzing user behavior to optimize both its website and its advertising.</p>
		<p>
			<strong>IP anonymization</strong>
		</p>
		<p>We have activated the IP anonymization feature on this website. Your IP address will be shortened by Google within the
			European Union or other parties to the Agreement on the European Economic Area prior to transmission to the United
			States. Only in exceptional cases is the full IP address sent to a Google server in the US and shortened there. Google
			will use this information on behalf of the operator of this website to evaluate your use of the website, to compile
			reports on website activity, and to provide other services regarding website activity and Internet usage for the
			website operator. The IP address transmitted by your browser as part of Google Analytics will not be merged with
			any other data held by Google.</p>
		<p>
			<strong>Browser plugin</strong>
		</p>
		<p>You can prevent these cookies being stored by selecting the appropriate settings in your browser. However, we wish to
			point out that doing so may mean you will not be able to enjoy the full functionality of this website. You can also
			prevent the data generated by cookies about your use of the website (incl. your IP address) from being passed to
			Google, and the processing of these data by Google, by downloading and installing the browser plugin available at
			the following link:
			<a href="https://tools.google.com/dlpage/gaoptout?hl=en" target="_blank">https://tools.google.com/dlpage/gaoptout?hl=en</a>.</p>
		<p>
			<strong>Objecting to the collection of data</strong>
		</p>
		<p>You can prevent the collection of your data by Google Analytics by clicking on the following link. An opt-out cookie
			will be set to prevent your data from being collected on future visits to this site:
			<a href="javascript:gaOptout();">Disable Google Analytics</a>.</p>
		<p>For more information about how Google Analytics handles user data, see Google's privacy policy:
            <a href="https://support.google.com/analytics/answer/6004245?hl=en"
                target="_blank">https://support.google.com/analytics/answer/6004245?hl=en</a>.</p>
        <p>
            <strong>Outsourced data processing</strong>
        </p>
        <p>We have entered into an agreement with Google for the outsourcing of our data processing and fully implement the strict
            requirements of the German data protection authorities when using Google Analytics.</p>
        <p>
            <strong>Demographic data collection by Google Analytics</strong>
        </p>
        <p>This website uses Google Analytics' demographic features. This allows reports to be generated containing statements about
			the age, gender, and interests of site visitors. This data comes from interest-based advertising from Google and
			third-party visitor data. This collected data cannot be attributed to any specific individual person. You can disable
			this feature at any time by adjusting the ads settings in your Google account or you can forbid the collection of
			your data by Google Analytics as described in the section "Refusal of data collection".</p>
  </div>
</template>

<script lang="ts">
	export default {
		name: 'googleAnalytics',
		props: [],
		mounted() {

		},
		data() {
			return {

			}
		},
		methods: {

		},
		computed: {

		}
}
</script>

<style scoped lang="scss">
	.google-analytics {

	}
</style>
