<template lang="html">
	<div>
		<h3>Matomo (formerly Piwik)</h3>
		<p>This website uses the open source web analytics service Matomo. Matomo uses so-called "cookies". These are text files
			that are stored on your computer and that allow an analysis of the use of the website by you. For this purpose, the
			information generated by the cookie about the use of this website is stored on our server. The IP address is anonymized
			before it is stored.</p>
		<p>Matomo cookies remain on your device until you delete them.</p>
		<p>The storage of Matomo cookies is based on Art. 6 (1) (f) DSGVO. The website operator has a legitimate interest in analyzing
			user behavior in order to optimize both its website and its advertising.</p>
		<p>The information generated by the cookies about your use of this website will not be disclosed to third parties. You can
			prevent these cookies being stored by selecting the appropriate settings in your browser. However, we wish to point
			out that doing so may mean you will not be able to enjoy the full functionality of this website.</p>
		<p>If you do not agree with the storage and use of your data, you can disable this feature here. In this case, an opt-out
			cookie will be stored in your browser to prevent Matomo from storing your usage data. If you delete your cookies,
			this will mean that the opt-out cookie will also be deleted. You will then need to reactivate it when you return
			to our site if you wish your activity not to be tracked.</p>
		<p>
			<em>
				<strong>
					<a style="color:#F00;" href="https://matomo.org/docs/privacy/" rel="nofollow" target="_blank">[Hier Matomo iframe-Code einfügen] (Klick für die Anleitung)</a>
				</strong>
			</em>
		</p>
  </div>
</template>

<script lang="ts">
	export default {
		name: 'matomo',
		props: [],
		mounted() {

		},
		data() {
			return {

			}
		},
		methods: {

		},
		computed: {

		}
}
</script>

<style scoped lang="scss">
	.matomo {

	}
</style>
