<template lang="html">
	<div>
		<h3>WordPress Stats</h3>
		<p>This website uses the WordPress Stats tool to perform statistical analyses of visitor traffic. This service is provided
			by Automattic Inc., 60 29th Street # 343, San Francisco, CA 94110-4929, USA.</p>
		<p>WordPress Stats uses cookies that are stored on your computer and allow an analysis of the use of the website. The information
			generated by the cookies about the use of our website is stored on servers in the USA. Your IP address will be anonymized
			after processing and before storage.</p>
		<p>WordPress Stats cookies remain on your device until you delete them.</p>
		<p>The storage of "WordPress Stats" cookies is based on Art. 6 (1) (f) DSGVO. The website operator has a legitimate interest
			in analyzing user behavior to optimize both its website and its advertising.</p>
		<p>You can configure your browser to inform you about the use of cookies so that you can decide on a case-by-case basis
			whether to accept or reject a cookie. Alternatively, your browser can be configured to automatically accept cookies
			under certain conditions or to always reject them, or to automatically delete cookies when closing your browser.
			The functionality of our services may be limited when cookies are disabled.</p>
		<p>You can object to the collection and use of your data at any time with future effect by clicking on this link and setting
			an opt-out cookie in your browser:
			<a href="https://www.quantcast.com/opt-out/" target="_blank">https://www.quantcast.com/opt-out/</a>.</p>
		<p>If you delete the cookies on your computer, you will have to set the opt-out cookie again.</p>
  </div>
</template>

<script lang="ts">
	export default {
		name: 'wordpressStats',
		props: [],
		mounted() {

		},
		data() {
			return {

			}
		},
		methods: {

		},
		computed: {

		}
}
</script>

<style scoped lang="scss">
	.wordpress-stats {

	}
</style>
